// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphql

type CreateLocalGuideInput struct {
	Title       string  `json:"title"`
	Description *string `json:"description,omitempty"`
	Location    string  `json:"location"`
}

type Guide struct {
	ID       string `json:"id"`
	Title    string `json:"title"`
	Content  string `json:"content"`
	Location string `json:"location"`
}

type LocalGuide struct {
	ID          string  `json:"id"`
	Title       string  `json:"title"`
	Description *string `json:"description,omitempty"`
	Location    string  `json:"location"`
	CreatedAt   string  `json:"createdAt"`
	UpdatedAt   string  `json:"updatedAt"`
}

type Mutation struct {
}

type Query struct {
}

type UpdateLocalGuideInput struct {
	Title       *string `json:"title,omitempty"`
	Description *string `json:"description,omitempty"`
	Location    *string `json:"location,omitempty"`
}
