package graphql

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.78

import (
	"context"
	"fmt"
)

// CreateLocalGuide is the resolver for the createLocalGuide field.
func (r *mutationResolver) CreateLocalGuide(ctx context.Context, input CreateLocalGuideInput) (*LocalGuide, error) {
	panic(fmt.Errorf("not implemented: CreateLocalGuide - createLocalGuide"))
}

// UpdateLocalGuide is the resolver for the updateLocalGuide field.
func (r *mutationResolver) UpdateLocalGuide(ctx context.Context, id string, input UpdateLocalGuideInput) (*LocalGuide, error) {
	panic(fmt.Errorf("not implemented: UpdateLocalGuide - updateLocalGuide"))
}

// DeleteLocalGuide is the resolver for the deleteLocalGuide field.
func (r *mutationResolver) DeleteLocalGuide(ctx context.Context, id string) (bool, error) {
	panic(fmt.Errorf("not implemented: DeleteLocalGuide - deleteLocalGuide"))
}

// LocalGuides is the resolver for the localGuides field.
func (r *queryResolver) LocalGuides(ctx context.Context) ([]*LocalGuide, error) {
	panic(fmt.Errorf("not implemented: LocalGuides - localGuides"))
}

// LocalGuide is the resolver for the localGuide field.
func (r *queryResolver) LocalGuide(ctx context.Context, id string) (*LocalGuide, error) {
	panic(fmt.Errorf("not implemented: LocalGuide - localGuide"))
}

// SearchGuides is the resolver for the searchGuides field.
func (r *queryResolver) SearchGuides(ctx context.Context, query string, location *string) ([]*Guide, error) {
	panic(fmt.Errorf("not implemented: SearchGuides - searchGuides"))
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
